name: BMI Calculator
on:
  push:
    branches:
      - main
jobs:
  calculating:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npx jest --testEnvironment=jsdom

      - name: Setup ssh keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: | 
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@${{ secrets.EC2_PUBLIC_IP }} 
          mkdir /home/ubuntu/bmi-calculator
          cd /home/ubuntu/bmi-calculator
          git clone git@github.com:vibck/github-workflow-bmi.git .
          npm install
          node server.js
